### ISSUE TITLE
A wrapper around CoreMotion.  

### ISSUE THREAD

**Issue by MHaroonBaig** [jeffkempista/MotionExample#1]
Sorry for opening up an issue but you can also use a very nice wrapper built around CoreMotion. It'll make things a little bit easier ;) 
https://github.com/MHaroonBaig/MotionKit

**Comment by jeffkempista** [comment]
Thank you @MHaroonBaig ! I'll check it out. 

I was just using this to play around with CoreMotion. But, thanks for looking and suggesting your MotionKit wrapper!

**Comment by MHaroonBaig** [comment]
My pleasure.
